### ISSUE TITLE
iAccess ODBC driver not found on Linux

### ISSUE THREAD

**Issue by jussihi** [soundstripe/iaccess#3]
Hello @soundstripe , I finally had the courage to test out your iAccess python wrapper! Too bad I'm having some problems using it, could you maybe help sort it out?

* i Access Db2 SQLAlchemy Driver version: iaccess==0.6.0, SQLAlchemy==2.0.29
* Python version: Python 3.11.8
* Operating System: Arch Linux

### Description

Tried to run the example program;
```
from sqlalchemy import create_engine

engine = create_engine('iaccess+pyodbc://user:pass@my_as400')
```

Output:
```
/home/jussi/iaccess_test/.venv/lib/python3.11/site-packages/iaccess/connector.py:21: IAccessDriverMissingWarning: driver "IBM i Access ODBC Driver" not found by pyodbc
install from https://www.ibm.com/support/pages/odbc-driver-ibm-i-access-client-solutions or specify an alternate driver name
available drivers: None
  warnings.warn(f'driver "{selected_driver}" not found by pyodbc\n'
```

However, I have the (latest) iAccess driver installed (acsbundle.jar, installed via `install_acs_64`);
```
(.venv) [jussi@jussi iaccess_test]$ ls /opt/ibm/
iAccessClientSolutions
(.venv) [jussi@jussi iaccess_test]$ ls /usr/share/applications/
 htop.desktop  'IBM i Access Client Solutions.desktop'  
```

Should I be using some other version of this driver or something..?

**Comment by jussihi** [comment]
I have also selected to install the database tools during acs installation;
![image](https://github.com/soundstripe/iaccess/assets/25184163/4071d57e-ae83-481e-917e-de367d192eb0)

**Comment by jussihi** [comment]
It seems Arch didn't quite like the installation, and since there was no ready-made package for ibm-iaccess (unlike for Debian, Ubuntu), I had to create my own; https://aur.archlinux.org/packages/ibm-iaccess . This solved the issue. Thank you for this repo!

**Comment by soundstripe** [comment]
Hey @jussihi thanks for trying this out, and also for ... answering your own question!

I hate that there is often the hurdle of installing the binary driver from IBM from behind a sign-in wall, but I guess they have their reasons for that.

Looks like maybe other Arch users will be able to benefit from your package, so that's excellent.

**Comment by jussihi** [comment]
@soundstripe yes :)

Actually you could update your readme with Linux installation instructions, as there are nowadays openly-available odbc drivers for major linux distros (and now for Arch Linux too, heh); https://kadler.io/blog/2022-05-20-odbc-repos/ These packages and package manager repos are maintained by IBM... i.e. they are official packages
